# Generated by Django 5.2 on 2026-06-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0003_agendaitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
