# Generated by Django 5.2 on 2026-07-03 21:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0004_alter_reference_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reference/')),
                ('original_name', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='gtd.reference')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
