# Generated by Django 5.2 on 2026-07-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_step_minutes', models.PositiveSmallIntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (30, '30 minutes'), (60, '1 hour')], default=15)),
                ('time_format', models.CharField(choices=[('12', '12-hour (5:30 p.m.)'), ('24', '24-hour (17:30)')], default='12', max_length=2)),
                ('date_style', models.CharField(choices=[('month_first', 'Month first (Jul 4, 2026)'), ('day_first', 'Day first (4 Jul 2026)'), ('iso', 'ISO (2026-07-04)')], default='month_first', max_length=20)),
            ],
            options={
                'verbose_name': 'preferences',
                'verbose_name_plural': 'preferences',
            },
        ),
    ]
