# Generated by Django 5.2 on 2026-06-27 05:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('disposition', models.CharField(choices=[('pending', 'Pending'), ('trashed', 'Trashed'), ('done_immediately', 'Done immediately'), ('delegated', 'Delegated'), ('action_created', 'Action created'), ('project_created', 'Project created'), ('someday_created', 'Someday/maybe created'), ('reference_created', 'Reference created')], default='pending', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
