# Generated by Django 5.2 on 2026-06-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='disposition',
            field=models.CharField(choices=[('pending', 'Pending'), ('trashed', 'Trashed'), ('done_immediately', 'Done immediately'), ('delegated', 'Delegated'), ('action_created', 'Action created'), ('project_created', 'Project created'), ('someday_created', 'Someday/maybe created'), ('reference_created', 'Reference created'), ('action_added_to_project', 'Action added to project')], default='pending', max_length=50),
        ),
    ]
