# Generated by Django 5.2 on 2026-06-26 20:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gtd', '0004_alter_reference_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_on', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gtd.meeting')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('disposition', models.CharField(choices=[('pending', 'Pending'), ('trashed', 'Trashed'), ('done_immediately', 'Done immediately'), ('delegated', 'Delegated'), ('action_created', 'Action created'), ('project_created', 'Project created'), ('someday_created', 'Someday/maybe created'), ('reference_created', 'Reference created'), ('action_added_to_project', 'Action added to project')], default='pending', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_notes', to='meetings.meetingsession')),
            ],
            options={
                'ordering': ['captured_at'],
            },
        ),
    ]
